name: Publish Package to GitHub NPM Registry

on: 
  release
    
jobs:
    npm-package:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: setup nodejs
          uses: actions/setup-node@v4
          with:
            node-version: 20.1
            cache: 'npm'
            registry-url: "https://npm.pkg.github.com"

        - name: install npm dependencies
          run: npm install    
